market/urls.py
from jet.dashboard.dashboard_modules import google_analytics_views
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import DashboardView
from checkout.views import CheckoutTestView, CheckoutAjaxView
from products.views import UserLibraryListView


urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^notifications/', include('pinax.notifications.urls')),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^review/', include('review.urls')),
    url(r'^', include('django_private_chat.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^library/', UserLibraryListView.as_view(), name='library'),    
]
# 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from .views import (
					SellerDashboard,
					SellerTransactionListView,
					SellerProductDetailRedirectView
				)
from products.views import (
					ProductCreateView,
					SellerProductListView,
					ProductUpdateView,
				)


urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transactions/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'),
    url(r'^products/(?P<pk>\d+)/$', SellerProductDetailRedirectView.as_view()),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
]

tags/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from .views import (
					TagListView,
					TagDetailView,
				)


urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
    

]

billing/models.py
from django.conf import settings
from django.db import models

from products.models import Product


class Transaction(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	product = models.ForeignKey(Product)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=10.99, verbose_name='Market price')
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	success = models.BooleanField(default=True)
	#transaction_id_payment_system = Braintree / Stripe
	# payment_method
	# last_four


	def __str__(self):
		return "%s" %(self.id)

sellers/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models





class SellerAccount(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_sellers", blank=True)
	active = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)



	def __str__(self):
		return str(self.user.username)


	def get_absolute_url(self):
		return reverse("products:vendor_detail", kwargs={"vendor_name": self.user.username})

sellers/forms.py
from django import forms






class NewSellerForm(forms.Form):
	agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)
	

dashboard/views.py
import random
from django.views import View
from django.shortcuts import render

from products.models import Product, CuratedProducts



class DashboardView(View):
	def get(self, request, *args, **kwargs):
		tag_views = None
		products = None
		top_tags = None
		curated = CuratedProducts.objects.filter(active=True).order_by("?")
		try:
			tag_views=request.user.tagview_set.all().order_by('-count')[:5]
		except:
			pass

		owned = None
		try:
			owned = request.user.myproducts.products.all()
		except:
			pass
		if tag_views:
			top_tags = [x.tag for x in tag_views]
			products = Product.objects.filter(tag__in=top_tags)
			if owned:
				products = products.exclude(pk__in=owned)

			if products.count() < 10:
				products = Product.objects.all().order_by('?')
				if owned:
					products = products.exclude(pk__in=owned)
				products = products[:10]
			else:
				products = products.distinct()
				products = sorted(products, key= lambda x: random.random())
		template = "dashboard/view.html"
		context = {
			"products":products,
			"top_tags":top_tags,
			"curated":curated,
		}
		return render(request, template, context)

sellers/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.shortcuts import get_object_or_404
from django.views.generic.base import RedirectView


from market.mixins import LoginRequiredMixin

from .forms import NewSellerForm
from .models import SellerAccount
from .mixins import SellerAccountMixin

from billing.models import Transaction
from products.models import Product



class SellerProductDetailRedirectView(RedirectView):

    permanent = True
    # query_string = True
    # pattern_name = 'article-detail'

    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()


class SellerTransactionListView(SellerAccountMixin, ListView):
	model = Transaction
	template_name = "sellers/transaction_list_view.html"

	def get_queryset(self):
		return self.get_transactions()


class SellerDashboard(SellerAccountMixin, FormMixin, View):
	form_class = NewSellerForm
	success_url = '/seller/'

	def post(self, request, *args, **kwargs):
		form = self.get_form()
		if form.is_valid():
		    return self.form_valid(form)
		else:
		    return self.form_invalid(form)


	def get(self, request, *args, **kwargs):
		apply_form = NewSellerForm()
		# account = SellerAccount.objects.filter(user=self.request.user)
		account = self.get_account()
		exists = account
		active = None
		template = 'sellers/dashboard.html'
		context = {}
		if exists:
			# account = account.first()
			active = account.active
		if not exists and not active:
			context["title"] = "Apply for Account"
			context["apply_form"] = apply_form
		elif exists and not active:
			context["title"] = "Account Pending"
		elif exists and active:
			context["title"] = "Seller Dashboard"
			# products = Product.objects.filter(seller=account)
			context["products"] = self.get_products()
			transactions = self.get_transactions()
			transactions_today = self.get_transactions_today()
			context["transactions_today"] = transactions_today
			context["today_sales"] = self.get_today_sales()
			context["total_sales"] = self.get_total_sales()
			context["transactions"] = transactions[:5] #.exclude(pk__in=transactions_today)
		else:
			pass

		return render(request, template, context)


	def form_valid(self, form):
		valid_data = super(SellerDashboard, self).form_valid(form) 
		obj = SellerAccount.objects.create(user=self.request.user)
		return valid_data 

templates/sellers/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>{{ title }}</h1>


{% if  apply_form %}
<form method="POST" action=''> {% csrf_token %}
<h4>Rules of the Marketplace</h4>
	<ol>
		<li>Be kind</li>
		<li>Sell well</li>
		<li>Don't steal</li>
	</ol>
	{{ apply_form.as_p }}
	<br>
	<input type="submit">
</form>
{% endif %}

<div class="row">
	<div class="col-sm-7">
		
		
		{% if transactions %}
		<h4>Today's sales are ${{ today_sales }}</h4>

		{% include "sellers/transaction_list.html" with transaction_list=transactions_today %}
		
		<br>
			<h4>Recent Transaction History (Total Sales: ${{ total_sales }})</h4>
			{% include "sellers/transaction_list.html" with transaction_list=transactions %}

		<p>
			<a href='{% url "sellers:transactions" %}'>View all transactions</a>
		</p>

		{% endif %}
	</div>	
	<div class="col-sm-5">
		<!-- <h4>Sold</h4> -->
		{% if products %}
		<h5>My Products<br><small><a href="{% url 'sellers:product_create' %}">Add</a> | <a href="{% url 'sellers:product_list' %}">View All</a></small></h5>
		<ul>
	        {% include "products/product_list_snippet.html" with product_list=products %}
		</ul>
		{% endif %}
	</div>
</div>

{% endblock %}

templates/sellers/product_list_view.html
{% extends "base.html" %}

{% load get_thumbnail %}



{% block content %}
<div class="col-sm-4">
	<p>
		<form method="GET" action="">
			<input type="text" name="q" placeholder="Search" value='{{ request.GET.q }}'>
			<input type="submit" value="search">
		</form>
	</p>
</div>
<h2>My Listed Products</h2>
<table class="table">
        {% for item in product_list %}
	   	<tr>
	   		<td> {{ item.id }} </td>
		    <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
		    <td> 
		    {% if item|get_thumbnail:'micro' %}
		    <a href="{{ item.get_absolute_url }}">
		    	<img src="{{ item|get_thumbnail:'micro' }}" style="max-width: 100px;">
		    </a>
		    <!-- <br> -->
		    {% endif %}
		    </td>
		    <td><span>had for - {{ item.age }}</span></td>
		    <td><span>Market price: ${{ item.price_1 }}</span></td>
		    <td><span>My price: ${{ item.price_2 }}</span></td>
		    <td><a href="{{ item.get_edit_url }}">Edit</a> | <a href="#">Delete</a></td>
			{% empty %}
				<li>No Products yet.</li>
		<hr>
		</tr>
		{% endfor %}
</table>

{% endblock %}

templates/sellers/transaction_list.html
<table class="table">
	<thead>
	<th>Product</th>
	<th>User</th>
	<th>Sale Total</th>
	<th></th>
	</thead>
	<tbody>
		{% for trans in transaction_list %}
		<tr>
			<td><span>{{ trans.product }}</span></td>
			<td><span>{{ trans.user }}</span></td>
			<td><span>{{ trans.price }}</span></td>
			<td>{{ trans.timestamp|timesince }} ago</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

templates/sellers/transaction_list_view.html
{% extends "base.html" %}

{% block content %}
<!-- <div class="col-sm-4">
	<p>
		<form method="GET" action="">
			<input type="text" name="q" placeholder="Search" value='{{ request.GET.q }}'>
			<input type="submit" value="search">
		</form>
	</p>
</div> -->
<h2>Transactions</h2>
<ul>
        {% include "sellers/transaction_list.html" with transaction_list=object_list %}
</ul>

{% endblock %}